name: Auto Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: rnd_8c75ZPu09TTF9eFldKn23Ja5l6kY

          RENDER_SERVICE_ID: srv-d0u6s53e5dus738poij0
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/deploy/$RENDER_SERVICE_ID